apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-templates
data:
  db-config.tpl: |-
{{ .Files.Get "files/templates/db-config.tpl" | indent 4 }}
  api-config.tpl: |-
{{ .Files.Get "files/templates/api-config.tpl" | indent 4 }}