apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.rules: |-
    groups:
    - name: devopscube demo alert
      rules:
      - alert: High Pod Memory
        expr: sum(container_memory_usage_bytes) > 1
        for: 1m
        labels:
          severity: slack
        annotations:
          summary: High Memory Usage
  prometheus.yml: |-
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.kube-system.svc.cluster.local:8080']
            labels:
              app: jkube-state-metrics
      - job_name: 'jenkins'
        static_configs:
          - targets: ['10.1.6.238:8080']
            labels:
              app: jenkins-server
              team: hsbclink
              monitor: true
      - job_name: 'jenkins-link'
        static_configs:
          - targets: ['10.1.6.238:8090']
            labels:
              app: jenkins-server
